name: Download Pro Match Data by Year

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Enter year (e.g., 2025)"
        required: true
        default: "2025"

jobs:
  download-pro:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install gdown
        run: pip install gdown

      - name: Download all files from Google Drive
        run: |
          mkdir -p data/pro_raw
          gdown --folder "https://drive.google.com/drive/folders/1gLSw0RLjBbtaNy0dgnGQDAZOHIgCe-HH" -O data/pro_raw
          echo " All files downloaded."
          ls -al data/pro_raw

      - name: Keep only the selected year
        run: |
          year=${{ github.event.inputs.year }}
          file_name="${year}_LoL_esports_match_data_from_OraclesElixir.csv"
          echo "Filtering file: $file_name"
          if [ -f "data/pro_raw/$file_name" ]; then
            mv "data/pro_raw/$file_name" "data/pro_raw/pro_${year}.csv"
          else
            echo "⚠️ File not found for ${year}"
            exit 1
          fi
          find data/pro_raw -type f ! -name "pro_${year}.csv" -delete
          echo " Remaining file:"
          ls -al data/pro_raw

      - name: Upload artifact (only selected year)
        uses: actions/upload-artifact@v4
        with:
          name: pro_${{ github.event.inputs.year }}
          path: data/pro_raw/pro_${{ github.event.inputs.year }}.csv
          if-no-files-found: error
          retention-days: 14
