name: Download Pro Match Data by Year

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Enter year (e.g., 2025)"
        required: true
        default: "2025"

jobs:
  download-pro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install gdown
        run: pip install gdown

      - name: Download file from Google Drive by year
        run: |
          mkdir -p data/pro_raw
          year=${{ github.event.inputs.year }}
          file_name="${year}_LoL_esports_match_data_from_OraclesElixir.csv"
          echo "Downloading file: $file_name"
          gdown --folder "https://drive.google.com/drive/folders/1gLSw0RLjBbtaNy0dgnGQDAZOHIgCe-HH" -O data/pro_raw
          mv data/pro_raw/$file_name data/pro_raw/pro_${year}.csv || echo "File not found for ${year}"
      - name: List downloaded files
        run: ls -al data/pro_raw
